{
 "title": "Mainnet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TO REQUEST (RATE)",
   "type": "graph",
   "description": "The per-second rate of toRequest as measured over the last 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_toRequest{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_toRequest{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_toRequest{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_toRequest{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "TO REPLY (RATE)",
   "type": "graph",
   "description": "The per-second rate of toReply as measured over the last 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_toReply{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_toReply{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_toReply{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_toReply{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "TO PROCESS (RATE)",
   "type": "graph",
   "description": "The per-second rate of toProcess as measured over the last 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_toProcess{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_toProcess{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_toProcess{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_toProcess{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "TO BROADCAST (RATE)",
   "type": "graph",
   "description": "The per-second rate of toBroadcast as measured over the last 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_toBroadcast{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_toBroadcast{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_toBroadcast{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_toBroadcast{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "SYNC CHECK ",
   "type": "graph",
   "description": "current round - latest solid round ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "main_validator_1_syncCheck", "legendFormat": "main_validator_1" },
    { "expr": "main_relayer_1_syncCheck", "legendFormat": "main_relayer_1" },
    { "expr": "main_relayer_2_syncCheck", "legendFormat": "main_relayer_2" },
    { "expr": "main_relayer_3_syncCheck", "legendFormat": "main_relayer_3" }
   ]
  },
  {
   "title": "TRANSACTION (TOTAL)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "main_relayer_1_totalTransactions",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "main_relayer_2_totalTransactions",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "main_relayer_3_totalTransactions",
     "legendFormat": "main_relayer_3"
    },
    {
     "expr": "relayer_stmpe_ml_totalTransactions",
     "legendFormat": "relayer_stmpe"
    },
    {
     "expr": "backend_stmpe_ml_totalTransactions",
     "legendFormat": "backend_stmpe"
    },
    {
     "expr": "main_validator_1_totalTransactions",
     "legendFormat": "main_validator_1"
    },
    {}
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "description": "The per-second rate of totalTransactions as measured over the last 10 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(main_relayer_1_totalTransactions{job=\"prometheus\"}[10m]) ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": " rate(main_relayer_2_totalTransactions{job=\"prometheus\"}[10m]) ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": " rate(main_relayer_3_totalTransactions{job=\"prometheus\"}[10m]) ",
     "legendFormat": "main_relayer_3"
    },
    {
     "expr": " rate(main_validator_1_totalTransactions{job=\"prometheus\"}[10m]) ",
     "legendFormat": "main_validator_1"
    }
   ]
  },
  {
   "title": "NON-SOLID (RATE)",
   "type": "graph",
   "description": "The per-second rate of nonSolid as measured over the last 10 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(main_validator_1_nonSolid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_nonSolid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_nonSolid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_nonSolid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    },
    {
     "expr": "rate(relayer_stmpe_ml_nonSolid{job=\"prometheus\"}[10m])",
     "legendFormat": "relayer_stmpe"
    },
    { "expr": "backend_stmpe_ml_nonSolid", "legendFormat": "backend_stmpe" }
   ]
  },
  {
   "title": "GET NODE INFO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_getNodeInfo{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_getNodeInfo{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_getNodeInfo{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3getNodeInfo{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "LAST SOLID 10m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    },
    {
     "expr": "rate(relayer_stmpe_ml_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "relayer_stmpe"
    },
    {
     "expr": "rate(backend_stmpe_ml_solid{job=\"prometheus\"}[10m])",
     "legendFormat": "backend_stmpe"
    }
   ]
  },
  {
   "title": "WERE ADDRESSES SPENT FROM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_wereAddressesSpentFrom{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_wereAddressesSpentFrom{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_wereAddressesSpentFrom{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_wereAddressesSpentFrom{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "STORE TRANSACTIONS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_storeTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_storeTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_storeTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_storeTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "GET TRANSACTIONS TO APPROVE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate(main_validator_1_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": " rate(main_relayer_1_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": " rate(main_relayer_2_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": " rate(main_relayer_3_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_3"
    },
    {
     "expr": " rate(relayer_stmpe_ml_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "relayer_stmpe"
    },
    {
     "expr": " rate(backend_stmpe_ml_getTransactionsToApprove{job=\"prometheus\"}[10m])  ",
     "legendFormat": "backend_stmpe"
    }
   ]
  },
  {
   "title": "NODE STORE TRANSACTIONS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_nodeStoredTx{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_nodeStoredTx{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_nodeStoredTx{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_nodeStoredTx{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "FIND TRANSACTIONS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_findTransactions{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_findTransactions{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_2_findTransactions{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_findTransactions{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "BROADCAST TRANSACTION",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_broadcastTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_broadcastTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_broadcastTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_broadcastTransactions{job=\"prometheus\"}[10m])  ",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "GET TRANSACTION STRINGS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_getTransactionStrings{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_getTransactionStrings{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_getTransactionStrings{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_getTransactionStrings{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "INVALID TIMESTAMP FAILURE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "main_validator_1_invalidTimestamp{job=\"prometheus\"}",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "main_relayer_1_invalidTimestamp{job=\"prometheus\"} ",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "main_relayer_2_invalidTimestamp{job=\"prometheus\"} ",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "main_relayer_3_invalidTimestamp{job=\"prometheus\"} ",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "VALID MILESTONES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(main_validator_1_milestoneValid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "rate(main_relayer_1_milestoneValid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "rate(main_relayer_2_milestoneValid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "rate(main_relayer_3_milestoneValid{job=\"prometheus\"}[10m])",
     "legendFormat": "main_relayer_3"
    }
   ]
  },
  {
   "title": "INCONSISTENT BALANCE FAILURE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "main_validator_1_inconsistentBalance{job=\"prometheus\"}",
     "legendFormat": "main_validator_1"
    },
    {
     "expr": "main_relayer_1_inconsistentBalance{job=\"prometheus\"}",
     "legendFormat": "main_relayer_1"
    },
    {
     "expr": "main_relayer_2_inconsistentBalance{job=\"prometheus\"}",
     "legendFormat": "main_relayer_2"
    },
    {
     "expr": "main_relayer_3_inconsistentBalance{job=\"prometheus\"}",
     "legendFormat": "main_relayer_3"
    }
   ]
  }
 ]
}